optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 150
  batch_size: 512
  save_model: true
  log_loss: false
  test_step: 1
  reproducible: true
  seed: 2023
  early_stop: True
  patience: 20

test:
  metrics: [mrr, ndcg]
  k: [5, 10, 20]
  batch_size: 512

data:
  type: sequential
  name: music
  seq_aug: true

model:
  name: mgrec
  dropout_rate: 0.1
  graph_dropout_prob: 0.3
  n_layers: 2
  embedding_size: 64
  n_heads: 2
  max_seq_len: 50
  cl_lambda: 1.0e-4
  cl_temp: 0.8
  weight_mean: 0.4
  sim_group_k: 4
  kl_weight: 1.0e-2

tune:
  enable: false
  hyperparameters: [cl_lambda, weight_mean]
  cl_lambda: [1.0e-4, 1.0e-3, 1.0e-2]
  weight_mean: [0.4, 0.5, 0.6]

bre:
  bre_model_name: "bert-base-uncased"
  bre_max_len: 32
  out_dim: 64
  dropout: 0.2
  bre_freeze_bert: true
  bre_pooling: "mean"
  bre_normalize: true